name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: バグの内容を簡潔に記載してください
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: バグの再現方法を記載してください
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: 期待する挙動を記載してください
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: 実際の挙動を記載してください
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: バグが発生した環境を記載してください
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: その他の情報を記載してください
    validations:
      required: false
