name: cron

on:
  schedule:
    # every week at 00:00
    - cron: '0 0 * * 0'

jobs:
  test-workflow:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: echo "Hello World"
